var assign2 = require('assign2-maitraiya')
var add = assign2.add(3,2)
var mul = assign2.sub(3,2)
var sub = assign2.mul(3,2)
var div = assign2.div(3,0)
console.log('Addition : '+add)
console.log('Subtraction : '+sub)
console.log('Multiplication : '+mul)
console.log('Division :'+div)
